name: Update Friend Checker Data

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch:
  repository_dispatch:
    types: [external_update]
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FRIEND_CHECKER_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run app.js
        run: node app.js

      - name: Move result.json to /api/static/data.json
        run: |
          mv result.json api/static/data.json

      - name: Commit and push data.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add api/static/data.json
          git commit -m 'chore: update data.json [auto]' || echo 'No changes to commit'
          git push
